### ISSUE TITLE
Notebook.ipynb fails to execute

### ISSUE THREAD

**Issue by davidbrochart** [QuantStack/jupytercad#175]
In notebook `examples/Notebook.ipynb`, this cell fails to execute:
```py
from jupytercad import CadDocument

doc = CadDocument("examples/example3.FCStd")

doc
```
![image](https://github.com/QuantStack/jupytercad/assets/4711805/cd9a5cf8-f98b-4c9b-9574-bb4e41ad4549)
```
[E 2023-06-02 15:40:05.639 YDocExtension] Error watching file: examples/examples/example3.FCStd
    HTTPError()
    Traceback (most recent call last):
      File "/home/david/micromamba/envs/jupytercad/lib/python3.9/site-packages/jupyter_collaboration/loaders.py", line 170, in _watch_file
        await self.notify()
      File "/home/david/micromamba/envs/jupytercad/lib/python3.9/site-packages/jupyter_collaboration/loaders.py", line 183, in notify
        model = await ensure_async(self._contents_manager.get(path, content=False))
      File "/home/david/micromamba/envs/jupytercad/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/home/david/micromamba/envs/jupytercad/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 877, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: examples/examples/example3.FCStd)
```

**Comment by martinRenou** [comment]
Oh yes! This is due to JupyterLab 4.0.1 which fixed an issue with the drive path. Prior to this version we had to use a path relative to where the server was started, not relative to the Notebook. This has been fixed and we need to update the path in the Notebook to the proper relative path `example3.FCStd`
