### ISSUE TITLE
Launch failure caused by TypeError __root__ instead of pydantic.RootModel

### ISSUE THREAD

**Issue by jonititan** [QuantStack/jupytercad#207]
I've tried installing 0.3.1,0.3.2, & 0.3.3 into a clean new environment from conda but all fail to launch from the shell with the same error.  Also fails when installed from pip.  Tried this on Linux 22 & Windows 10

launch is as instructed in documentation 

[jupyter cad](https://jupytercad.readthedocs.io/en/latest/app.html)

```
Traceback (most recent call last):

  File "/home/jonititan/miniconda3/envs/cad/bin/jupyter-cad", line 6, in <module>

    from jupytercad.cadapp import main

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/jupytercad/__init__.py", line 4, in <module>

    from .notebook import *  # noqa

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/jupytercad/notebook/__init__.py", line 1, in <module>

    from .cad_document import CadDocument  # noqa

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/jupytercad/notebook/cad_document.py", line 15, in <module>

    from jupytercad.notebook.objects._schema.any import IAny

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/jupytercad/notebook/objects/__init__.py", line 8, in <module>

    from ._schema.jcad import Parts, ShapeMetadata  # noqa

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/jupytercad/notebook/objects/_schema/jcad.py", line 49, in <module>

    class JcadModel(BaseModel):

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 95, in __new__

    private_attributes = inspect_namespace(

  File "/home/jonititan/miniconda3/envs/cad/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 279, in inspect_namespace

    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")

TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
```

**Comment by trungleduc** [comment]
Hi, can you try to downgrade `pydantic` to 1.10.11?

**Comment by jonititan** [comment]
I  downgraded using 
```
conda install pydantic=1.10.11 
```
and it now works on both the linux and the windows machine.  

Thank you

**Comment by martinRenou** [comment]
I believe we should keep the issue open to track supporting the latest pydantic
